
name: Make A Database
on: push
jobs:
  MySQL:
    runs-on: ubuntu-latest
    env:
      MYSQL_PWD: password
    services:
      test_db:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: VerySecret!123
        options: >- 
          --health-cmd="mysql -uroot -p\"$MYSQL_ROOT_PASSWORD\" -e 'SHOW DATABASES;'" 
          --health-interval=5s 
          --health-timeout=2s 
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Make It Easy
        run: |
          touch ~/.my.cnf
          mysql_config_editor reset
          mysql_config_editor set \
          --host=127.0.0.1 \
          --port=${{ job.services.test_db.ports[3306] }} \
          --user=$MYSQL_USER \
          --login-path=test_db
        env:
          MYSQL_USER: root
      - name: Show Me Them Databases
        run: |
          echo "💾 The Following Databases Are Available"
          mysql --login-path=test_db <<EOF
              DROP DATABASE IF EXISTS fuck_everything;
              CREATE DATABASE fuck_everything;
          EOF
          mysql --login-path=test_db -e "SHOW DATABASES;"
        env:
          MYSQL_PWD: VerySecret!123
      - name: Do Some Migrations
        uses: docker://liquibase/liquibase
        with:
          args: >-
            --username=root
            --password=VerySecret\!123
            --classpath=src
            --changeLogFile=sample.yaml
            --url=jdbc:mysql://test_db:${{ job.services.mysql.ports[3306] }}/fuck_everything
            --logLevel=debug
            status
            --verbose
