
name: Make A Database
on: push
jobs:
  MySQL:
    runs-on: ubuntu-latest
    env:
      MYSQL_PWD: password
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: VerySecret!123
        options: >- 
          --health-cmd="mysql -uroot -p\"$MYSQL_ROOT_PASSWORD\" -e 'SHOW DATABASES;'" 
          --health-interval=5s 
          --health-timeout=2s 
          --health-retries=3
    steps:
      - name: Make It Easy
        run: |
          touch ~/.my.cnf
          mysql_config_editor reset
          mysql_config_editor set \
          --host=127.0.0.1 \
          --port=${{ job.services.mysql.ports[3306] }} \
          --user=$MYSQL_USER
          --login-path=test_db
        env:
          MYSQL_USER: root
      - name: Show Me Them Databases
        run: |
          echo "💾 The Following Databases Are Available"
          mysql --login-path=test_db <<EOF
              DROP DATABASE IF EXISTS mfp_dev_challenges;
              DROP DATABASE IF EXISTS mfp_dev_food;
              DROP DATABASE IF EXISTS mfp_dev_main;
              DROP DATABASE IF EXISTS mfp_dev_plans;
              DROP DATABASE IF EXISTS mfp_dev_shard0;
              CREATE DATABASE mfp_dev_challenges;
              CREATE DATABASE mfp_dev_food;
              CREATE DATABASE mfp_dev_main;
              CREATE DATABASE mfp_dev_plans;
              CREATE DATABASE mfp_dev_shard0;
          EOF
        env:
          MYSQL_PWD: VerySecret!123
      - name: Do Some Migrations
        uses: docker://liquibase/liquibase
        with:
          args: --version
