
name: Make A Database
on: push
jobs:
  MySQL:
    runs-on: ubuntu-latest
    env:
      MYSQL_PWD: password
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_USER: test_db
          MYSQL_PASSWORD: VerySecret!123
          MYSQL_DATABASE: nothing_to_see_here
          MYSQL_ROOT_PASSWORD: qwekdj8whjiY7tgfyHUIO8y7t
        options: >- 
          --health-cmd="mysql -u\"$MYSQL_USER\" -p\"$MYSQL_PASSWORD\" -e 'SHOW DATABASES;'" 
          --health-interval=5s 
          --health-timeout=2s 
          --health-retries=3
    steps:
      - name: Make It Easy
        run: |
          touch ~/.my.cnf
          mysql_config_editor reset
          mysql_config_editor set \
          --host=127.0.0.1 \
          --port=${{ job.services.mysql.ports[3306] }} \
          --user=$MYSQL_USER
        env:
          MYSQL_USER: test_db
      - name: Show Me Them Databases
        run: |
          echo "💾 The Following Databases Are Available"
          mysql -e "SHOW DATABASES;"
        env:
          MYSQL_PWD: VerySecret!123
      - name: Do Some Migrations
        uses: docker://liquibase/liquibase
        with:
          args: --version
