
name: Initialize DB
on: push
jobs:
  SecureCredentials:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      db_user: root
      db_password: ${{ steps.random-password-generator.outputs.db_password }}
    steps:
    - id: random-password-generator
      run: |
       export CHARSET='A-Za-z0-9!$%=>?@'
       export RND_PASSWORD=$(head /dev/urandom | LC_ALL=C tr -dc $CHARSET | head -c 20)
       echo "$RND_PASSWORD"
       echo "::set-output name=db_password::$(echo $RND_PASSWORD)"
       echo "::set-output name=db_user::root"

  JobB:
    needs: SecureCredentials
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: ${{ needs.SecureCredentials.outputs.db_password }}
    steps:
      - name: Echo Me!
        run: echo "Hello THERE=== $MYSQL"

  JobC:
    runs-on: ubuntu-latest
    steps:
      - name: What
        run: docker --version
