
name: Initialize DB
on: push
jobs:
  SecureCredentials:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      db_user: root
      db_password: ${{ steps.random-password-generator.outputs.db_password }}
    steps:
    - id: random-password-generator
      run: |
       export CHARSET='A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~'
       export RND_PASSWORD=$(head /dev/urandom | LC_ALL=C tr -dc $CHARSET| head -c 13)
       echo "$RND_PASSWORD"
       echo "::set-output name=db_password::$(echo $RND_PASSWORD)"
       echo "::set-output name=db_user::root"
      shell: bash
  Job1:
    needs: SecureCredentials
    runs-on: ubuntu-latest
    steps:
      - name: Echo Me!
        run: |
          echo $MYSQL_ROOT_PASSWORD
          echo $MYSQL_USER
        env:
          MYSQL_ROOT_PASSWORD: ${{ needs.SecureCredentials.outputs.db_password }}
          MYSQL_USER: ${{ needs.SecureCredentials.outputs.db_user }}
